### ISSUE TITLE
CraftCMS's Controller.php's $this->request is string when loading Campaign settings

### ISSUE THREAD

**Issue by frankvolkel** [putyourlightson/craft-campaign#157]
### Describe the bug
CraftCMS's Controller.php's $this->request is string when loading Campaign settings, causing errors

```
Error: Call to a member function getIsLivePreview() on string in /application/vendor/craftcms/cms/src/web/Controller.php:133
Stack trace:
#0 /application/vendor/yiisoft/yii2/base/Controller.php(178): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /application/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('edit-general', Array)
#2 /application/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-general', Array)
#3 /application/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('campaign/settin...', Array)
#4 /application/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('campaign/settin...', Array)
#5 /application/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#6 /application/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 /application/web/index.php(61): yii\base\Application->run()
#8 {main}
```

### To reproduce
Steps to reproduce the behaviour:
1. Upgrade to Craft Pro 3.5.0-RC1.1
2. Navigate to /admin/campaign/settings/general
3. Error

### Expected behaviour
Campaign settings screen should load normally

### Screenshots
None

### Versions
- Plugin version: 1.15.4
- Craft version: Craft Pro 3.5.0-RC1.1

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/9ec0bab0075a9054e6ee984c1c7baf44574c76dc for the next release.
