### ISSUE TITLE
Database migration error while upgrading campaing

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#272]
### Describe the bug
When running upgrade migration failed with error below. Am running a Postgres database (v11). Assuming error is related to that.

```
*** applying m210903_120000_add_test_contact_ids_column
    > add column testContactIds text to table {{%campaign_campaigntypes}} ... done (time: 0.001s)
    > update in {{%campaign_campaigntypes}} ...Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "testcontactid" does not exist
LINE 1: ...ATE "campaign_campaigntypes" SET "testContactIds"=testContac...
                                                             ^
HINT:  Perhaps you meant to reference the column "campaign_campaigntypes.testContactId".
The SQL being executed was: UPDATE "campaign_campaigntypes" SET "testContactIds"=testContactId, "dateUpdated"='2021-10-06 21:07:42' (/app/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE "campaig...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE "campaig...')
#2 /app/vendor/craftcms/cms/src/db/Migration.php(277): yii\db\Command->execute()
#3 /app/vendor/putyourlightson/craft-campaign/src/migrations/m210903_120000_add_test_contact_ids_column.php(27): craft\db\Migration->update('{{%campaign_cam...', Array)
#4 /app/vendor/craftcms/cms/src/db/Migration.php(52): putyourlightson\campaign\migrations\m210903_120000_add_test_contact_ids_column->safeUp()
#5 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(385): yii\console\controllers\BaseMigrateController->migrateUp('m210903_120000_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#12 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#13 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#15 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /app/craft(22): yii\base\Application->run()
#17 {main}
*** failed to apply m210903_120000_add_test_contact_ids_column (time: 0.031s)
```

### Versions
- Plugin version: 1.19.2 -> was upgrading skipping three versions to 1.21.0
- Craft version: Craft Pro 3.6.17

**Comment by bencroker** [comment]
Thanks, released a fix for this in version 1.12.1.
