### ISSUE TITLE
TypeError on sendouts page after update to v1.22.0

### ISSUE THREAD

**Issue by michaelhue** [putyourlightson/craft-campaign#281]
### Describe the bug
Trying to access the sendouts page in the control page results in a TypeError:

> TypeError: putyourlightson\campaign\services\MailingListsService::getMailingListsByIds(): Argument #1 ($mailingListIds) must be of type array, int given, called in /src/vendor/putyourlightson/craft-campaign/src/elements/SendoutElement.php on line 692 and defined in /src/vendor/putyourlightson/craft-campaign/src/services/MailingListsService.php:54

Reverting to the previous version resolves the issue.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Campaign > Sendouts

### Versions
- Plugin version: 1.22.0
- Craft version: Craft Pro 3.7.20
- PHP version: 8.0.12

### Full stack trace

```
TypeError: putyourlightson\campaign\services\MailingListsService::getMailingListsByIds(): Argument #1 ($mailingListIds) must be of type array, int given, called in /src/vendor/putyourlightson/craft-campaign/src/elements/SendoutElement.php on line 692 and defined in /src/vendor/putyourlightson/craft-campaign/src/services/MailingListsService.php:54
Stack trace:
#0 /src/vendor/putyourlightson/craft-campaign/src/elements/SendoutElement.php(692): putyourlightson\campaign\services\MailingListsService->getMailingListsByIds(1, Array)
#1 /src/vendor/yiisoft/yii2/base/Component.php(140): putyourlightson\campaign\elements\SendoutElement->getMailingLists()
#2 /src/vendor/craftcms/cms/src/base/Element.php(1736): yii\base\Component->__get('mailingLists')
#3 /src/vendor/craftcms/cms/src/helpers/Template.php(90): craft\base\Element->__get('mailingLists')
#4 /src/storage/runtime/compiled_templates/37/375a737b6a79bb46b0cf3694e0109de1b775987f3e7ef2f9ab9a6d17e6dac36b.php(57): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(putyourlightson\campaign\elements\SendoutElement), 'mailingLists', Array)
#5 /src/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e9f1962b8425a63508b560ceda5e76d3925837cdcb5dfc5dc51bc489096a73a5->doDisplay(Array, Array)
#6 /src/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /src/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#8 /src/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#9 /src/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#10 /src/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('campaign/sendou...', Array)
#11 /src/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('campaign/sendou...', Array)
#12 /src/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('campaign/sendou...', Array, 'cp')
#13 /src/vendor/putyourlightson/craft-campaign/src/controllers/SendoutsController.php(324): craft\web\Controller->renderTemplate('campaign/sendou...', Array)
#14 [internal function]: putyourlightson\campaign\controllers\SendoutsController->actionEditSendout('regular', 32384, NULL, Object(putyourlightson\campaign\elements\SendoutElement))
#15 /src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /src/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#17 /src/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('edit-sendout', Array)
#18 /src/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('campaign/sendou...', Array)
#19 /src/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('campaign/sendou...', Array)
#20 /src/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#21 /src/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /src/web/index.php(25): yii\base\Application->run()
#23 /Users/michael/.composer/vendor/laravel/valet/server.php(219): require('/Users/michael/...')
#24 {main}
```

**Comment by bencroker** [comment]
Thanks @michaelhue! Fixed in https://github.com/putyourlightson/craft-campaign/commit/ec9c93d2e044331a77a7bdd17b2a644e3bd1f293 and released in version 1.22.1.
