### ISSUE TITLE
PHP Notice: Array to string conversion when creating new segment template

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#98]
### Describe the bug
When trying to create a new segment template, receive `PHP Notice: Array to string conversion`

### To reproduce
Steps to reproduce the behaviour:
1. Go to Campaign > Segments
2. Click on 'New Segment' and choose 'Template'
3. See error message `PHP Notice: Array to string conversion`

### Expected behaviour
To be able to create a New Segment Template

### Screenshots
Video of problem: https://jmp.sh/qIH4haE

### Versions
- Plugin version: 1.12.2
- Craft version: Craft Pro 3.3.16.3

### Full report
```
yii\base\ErrorException: Array to string conversion in /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/42/42adfe3568d0ca9f6a4788de6e4d608adde170f9ffee8ccf4fe57d413ede841e.php:99
Stack trace:
#0 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/Users/iamkeir/...', 99)
#1 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/42/42adfe3568d0ca9f6a4788de6e4d608adde170f9ffee8ccf4fe57d413ede841e.php(99): craft\web\ErrorHandler->handleError(8, 'Array to string...', '/Users/iamkeir/...', 99, Array)
#2 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7cb2eb91b0ac9b275fa5af27b220f199695104341491b8215cb722c81bf31ec0->doDisplay(Array, Array)
#3 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/d2/d270daa505fd9f67b51669dae495a522fd9b94e0bd0a363c30a7b855653ff391.php(414): Twig\Template->display(Array)
#5 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Extension/CoreExtension.php(1105): __TwigTemplate_c8ceb250b76a10fc90fccc0cf0c49bcc4b2599887cd6fb329149981e84a9edae->macro_textarea(Array)
#6 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/d2/d270daa505fd9f67b51669dae495a522fd9b94e0bd0a363c30a7b855653ff391.php(1032): twig_call_macro(Object(__TwigTemplate_c8ceb250b76a10fc90fccc0cf0c49bcc4b2599887cd6fb329149981e84a9edae), 'macro_textarea', Array, 166, Array, Object(Twig\Source))
#7 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Extension/CoreExtension.php(1105): __TwigTemplate_c8ceb250b76a10fc90fccc0cf0c49bcc4b2599887cd6fb329149981e84a9edae->macro_textareaField(Array)
#8 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/15/158823076bf6276449e402915227c27ff5702b2a2d7001a4a146f11fd87a6027.php(62): twig_call_macro(Object(__TwigTemplate_c8ceb250b76a10fc90fccc0cf0c49bcc4b2599887cd6fb329149981e84a9edae), 'macro_textareaF...', Array, 9, Array, Object(Twig\Source))
#9 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f9f9d9156757d8051c27d1eea99b8c00abf76f1d163eda9778004a5717b00803->doDisplay(Array, Array)
#10 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/02/0267d6302a317feda1016cc4a0f88ae602288b553d9c515a29297e9fcd82df6c.php(195): Twig\Template->display(Array)
#12 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_9b954fe7a76493d8efaae7d49815a631d5d091c3f776c729bb734c91a8a94de7->block_content(Array, Array)
#13 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(727): Twig\Template->displayBlock('content', Array, Array)
#14 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->block_main(Array, Array)
#15 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(576): Twig\Template->displayBlock('main', Array, Array)
#16 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(184): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->block_body(Array, Array)
#17 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/97/97f885eeec896c06cfeae354224d2663ef43197a6b1e61061ec80cf1cef9ec85.php(75): Twig\Template->displayBlock('body', Array, Array)
#18 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6aa451c8c76e9b2e5cdf3cdeef914a8ff8f581a1f29db00d1cc1f131efb6fd4d->doDisplay(Array, Array)
#19 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/12/128240ac9d49437d9e8ee94436e13b031b7c10f5b45dd23063b2a52e03752180.php(56): Twig\Template->display(Array, Array)
#21 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ce5f42e443a28710d82968b6dbf04f4284089c457f1c11ad16966293e9a9b524->doDisplay(Array, Array)
#22 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/82/8266e8a470accad67868929c36bb0409feb708496f343ac5a282929c9e70ca5a.php(118): Twig\Template->display(Array, Array)
#24 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_202b44ac9d554c55f49304257cee7d06e890a7eb4ac49356a880a2b4cf3390a5->doDisplay(Array, Array)
#25 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/5c/5c96d53cd2f4f63570c8475f6eb745289ad6209d19198c108cd72c799c7b7511.php(274): Twig\Template->display(Array, Array)
#27 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_42c72c7107f546442d17d062bc67e3e733baa1ad88421b8758dd118e7898fc40->doDisplay(Array, Array)
#28 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/a2/a2000c9728d7356bd4c083fbfd993bbe5b4178261e606e17628c0aa28d069329.php(50): Twig\Template->display(Array, Array)
#30 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9ab0f401bebcb2bc94b81a997090df7bf9c8be3f88fc345431c93fa871b2a9df->doDisplay(Array, Array)
#31 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /Users/iamkeir/Sites/ben/build/storage/runtime/compiled_templates/02/0267d6302a317feda1016cc4a0f88ae602288b553d9c515a29297e9fcd82df6c.php(64): Twig\Template->display(Array, Array)
#33 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9b954fe7a76493d8efaae7d49815a631d5d091c3f776c729bb734c91a8a94de7->doDisplay(Array, Array)
#34 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#35 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#36 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#37 /Users/iamkeir/Sites/ben/build/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#38 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('campaign/segmen...', Array)
#39 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('campaign/segmen...', Array)
#40 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('campaign/segmen...', Array)
#41 /Users/iamkeir/Sites/ben/build/vendor/putyourlightson/craft-campaign/src/controllers/SegmentsController.php(126): craft\web\Controller->renderTemplate('campaign/segmen...', Array)
#42 [internal function]: putyourlightson\campaign\controllers\SegmentsController->actionEditSegment('template', NULL, NULL, Object(putyourlightson\campaign\elements\SegmentElement))
#43 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#44 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#45 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-segment', Array)
#46 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-segment', Array)
#47 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('campaign/segmen...', Array)
#48 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('campaign/segmen...', Array)
#49 /Users/iamkeir/Sites/ben/build/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#50 /Users/iamkeir/Sites/ben/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#51 /Users/iamkeir/Sites/ben/build/web/index.php(21): yii\base\Application->run()
#52 {main}
```

**Comment by bencroker** [comment]
Thanks, working on a fix for this.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/b5fac589d1c507c7266761a81159983ecb1beb8f.
